# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f9a0fde6647aebca135cdde55e1e1a7f73b8d08f8d5dbd178686302c7d6723fbc945b01f471ef18ced3fe6372d26670817f859c5a2638ba7df5988c9e0dd6c90

test:
  secret_key_base: b6b962d63a00c0b059f75699e9deedd8475e58daf4aab90c1a43f3d781c82f473a2c80dc576ec712cc1ec19f2a9b90cfbc75cb08156899253ee38ce32f6ff4f9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
